identitatem/dex-operator

bundle/manifests/dex-operator.clusterserviceversion.yaml, config/manager/manager.yaml, controllers/dexserver_controller.go
DPANIC	controller-runtime.manager.controller.dexserver	odd number of arguments passed as key-value pairs for logging
=> add resources seeing log panic

Dockerfile
Part of https://github.com/open-cluster-management/backlog/issues/15130
=> Use prow dockerfile images

bundle/manifests/dex-operator.clusterserviceversion.yaml, config/manager/kustomization.yaml, config/manager/manager.yaml, config/rbac/role.yaml, controllers/dexserver_controller.go, controllers/mTLS.go, hack/community/rbac-dex-operator-dexsso-community.yaml
* fixed logging bug
* add secret and volume mount deployment
* cpu resource needed a bump to quickly generate the key pairs
=> implement create secret with Mutual TLS cert and key for server and client

api/v1alpha1/dexserver_types.go, config/crd/bases/auth.identitatem.io_dexservers.yaml
=> Make  clientsecret a global refernce

.gitignore, Makefile2.mak, README.md, bundle/manifests/auth.identitatem.io_dexservers.yaml, controllers/dexserver_controller.go, hack/generate-cr.sh
* Update the route parameters to be similar to meta cluster
* Dex needs tls defined, the insecure redirect should be the key here
=> change route settings to allow web

pkg/api/dex.go
=> Add withBlock

controllers/dexclient_controller.go, controllers/dexserver_controller.go
=> fix sonarcloud reliability C rating

Makefile2.mak, bundle/manifests/dex-operator.clusterserviceversion.yaml, controllers/dexclient_controller.go, controllers/dexserver_controller.go, controllers/mTLS.go, hack/generate-cr-all-in-one.sh
* change the grpc service name from 'dex' to 'grpc'
* now, access the service by 'grpc.$ns.svc.cluster.local' where previously, was just 'dex'
* this allows the controller to mange dex server instances in remote namespaces
=> generate tls based on service domain with namespace

controllers/dexclient_controller.go
=> Remove test not found on client secret

controllers/dexserver_controller.go, go.mod
=> Un-hardcode the org

pkg/api/dex.go
=> Add a withBlock to wait grpc connection

api/v1alpha1/dexserver_types.go
=> allow status conditions omitempty

bundle/manifests/dex-operator.clusterserviceversion.yaml, config/manager/manager.yaml, deploy/dex-server/deployment.yaml
Part of issue https://github.com/open-cluster-management/backlog/issues/17121
=> update tolerations and anti-affinity

config/rbac/role.yaml, controllers/dexclient_controller.go
https://github.com/open-cluster-management/backlog/issues/17225
=> Fixes while testing

controllers/dexserver_controller.go
https://github.com/open-cluster-management/backlog/issues/17259
=> Copy LDAP rootCA secret into dex server ns

api/v1alpha1/dexserver_types.go, controllers/dexserver_controller.go, go.mod, go.sum
=> Add deployment availability as a status condition to dex server

controllers/suite_test.go
Zenhub Issue [17474](https://github.com/open-cluster-management/backlog/issues/17474)
This PR builds on top of PR: https://github.com/identitatem/dex-operator/pull/91 and brings the coverage of the dexserver controller to 65.9%
=> Unit tests for dex server controller (part 2)

.github/workflows/release.yml, .github/workflows/test.yml, Dockerfile, go.mod
Signed-off-by: Leena Jawale <ljawale@redhat.com>
issue: https://github.com/open-cluster-management/backlog/issues/18501
=> update go version to 1.17

README.md
=> org rename stolostron

controllers/dexserver_controller.go
Signed-off-by: Vidya Nambiar <vnambiar@redhat.com>
=> Generate env var when client secret is created in dexserver namespace

deploy/dex-server/deployment.yaml
Signed-off-by: Leena Jawale <ljawale@redhat.com>
issue: https://github.com/stolostron/backlog/issues/17859
=> add label on deployment for easy logging

README.md
=> update doc concerning release and tag

controllers/dexserver_controller.go, controllers/dexserver_controller_test.go
https://github.com/stolostron/backlog/issues/19846
/hold
=> Add GroupSearch and LoadAllGroups

.triggerbuild
=> Trigger new build to pick up new UBI 8 ubi-minimal image for CVE fix

deploy/dex-server/deployment.yaml
Signed-off-by: Leena Jawale <ljawale@redhat.com>
issue: https://github.com/stolostron/backlog/issues/20689
=> add runAsNonRoot in dex-server deployement

.triggerbuild
For issue https://github.com/stolostron/backlog/issues/22159
=> force new build to pick up CVE base image fixes

Makefile
For issue https://github.com/stolostron/backlog/issues/23450
=> fix coverage filename so sonar gets results of coverage
